// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Post struct {
	ID                   uuid.UUID          `json:"id"`
	SourceID             uuid.UUID          `json:"source_id"`
	Title                string             `json:"title"`
	Url                  string             `json:"url"`
	Author               pgtype.Text        `json:"author"`
	SummaryShort         pgtype.Text        `json:"summary_short"`
	SummaryLong          pgtype.Text        `json:"summary_long"`
	SummaryStatus        string             `json:"summary_status"`
	SummaryAttempts      int32              `json:"summary_attempts"`
	SummaryNextAttemptAt pgtype.Timestamptz `json:"summary_next_attempt_at"`
	SummaryError         pgtype.Text        `json:"summary_error"`
	SummaryLastErrorKind pgtype.Text        `json:"summary_last_error_kind"`
	SummarizedAt         pgtype.Timestamptz `json:"summarized_at"`
	Tags                 []string           `json:"tags"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	PublishedAt          time.Time          `json:"published_at"`
	CreatedAt            time.Time          `json:"created_at"`
	Metadata             json.RawMessage    `json:"metadata"`
	SearchVector         interface{}        `json:"search_vector"`
}

type Source struct {
	ID         uuid.UUID          `json:"id"`
	Kind       string             `json:"kind"`
	Name       string             `json:"name"`
	SiteUrl    pgtype.Text        `json:"site_url"`
	FeedUrl    pgtype.Text        `json:"feed_url"`
	IconUrl    pgtype.Text        `json:"icon_url"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  time.Time          `json:"created_at"`
	LastPolled pgtype.Timestamptz `json:"last_polled"`
	Metadata   json.RawMessage    `json:"metadata"`
}
