// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (source_id, title, url, author, summary_short, summary_long, summary_status, tags, image_url, published_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, source_id, title, url, author, summary_short, summary_long, summary_status, summary_attempts, summary_next_attempt_at, summary_error, summary_last_error_kind, summarized_at, tags, image_url, published_at, created_at, metadata, search_vector
`

type CreatePostParams struct {
	SourceID      uuid.UUID       `json:"source_id"`
	Title         string          `json:"title"`
	Url           string          `json:"url"`
	Author        pgtype.Text     `json:"author"`
	SummaryShort  pgtype.Text     `json:"summary_short"`
	SummaryLong   pgtype.Text     `json:"summary_long"`
	SummaryStatus string          `json:"summary_status"`
	Tags          []string        `json:"tags"`
	ImageUrl      pgtype.Text     `json:"image_url"`
	PublishedAt   time.Time       `json:"published_at"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.SourceID,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.SummaryShort,
		arg.SummaryLong,
		arg.SummaryStatus,
		arg.Tags,
		arg.ImageUrl,
		arg.PublishedAt,
		arg.Metadata,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.SummaryShort,
		&i.SummaryLong,
		&i.SummaryStatus,
		&i.SummaryAttempts,
		&i.SummaryNextAttemptAt,
		&i.SummaryError,
		&i.SummaryLastErrorKind,
		&i.SummarizedAt,
		&i.Tags,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.SearchVector,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.source_id, p.title, p.url, p.author, p.summary_short, p.summary_long, p.summary_status, p.summary_attempts, p.summary_next_attempt_at, p.summary_error, p.summary_last_error_kind, p.summarized_at, p.tags, p.image_url, p.published_at, p.created_at, p.metadata, p.search_vector, s.name AS source_name, s.icon_url AS source_icon_url
FROM posts p
JOIN sources s ON p.source_id = s.id
WHERE p.id = $1
`

type GetPostRow struct {
	ID                   uuid.UUID          `json:"id"`
	SourceID             uuid.UUID          `json:"source_id"`
	Title                string             `json:"title"`
	Url                  string             `json:"url"`
	Author               pgtype.Text        `json:"author"`
	SummaryShort         pgtype.Text        `json:"summary_short"`
	SummaryLong          pgtype.Text        `json:"summary_long"`
	SummaryStatus        string             `json:"summary_status"`
	SummaryAttempts      int32              `json:"summary_attempts"`
	SummaryNextAttemptAt pgtype.Timestamptz `json:"summary_next_attempt_at"`
	SummaryError         pgtype.Text        `json:"summary_error"`
	SummaryLastErrorKind pgtype.Text        `json:"summary_last_error_kind"`
	SummarizedAt         pgtype.Timestamptz `json:"summarized_at"`
	Tags                 []string           `json:"tags"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	PublishedAt          time.Time          `json:"published_at"`
	CreatedAt            time.Time          `json:"created_at"`
	Metadata             json.RawMessage    `json:"metadata"`
	SearchVector         interface{}        `json:"search_vector"`
	SourceName           string             `json:"source_name"`
	SourceIconUrl        pgtype.Text        `json:"source_icon_url"`
}

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.SummaryShort,
		&i.SummaryLong,
		&i.SummaryStatus,
		&i.SummaryAttempts,
		&i.SummaryNextAttemptAt,
		&i.SummaryError,
		&i.SummaryLastErrorKind,
		&i.SummarizedAt,
		&i.Tags,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.SearchVector,
		&i.SourceName,
		&i.SourceIconUrl,
	)
	return i, err
}

const listPendingSummaries = `-- name: ListPendingSummaries :many
SELECT id, source_id, title, url, author, summary_short, summary_long, summary_status, summary_attempts, summary_next_attempt_at, summary_error, summary_last_error_kind, summarized_at, tags, image_url, published_at, created_at, metadata, search_vector FROM posts
WHERE summary_status = 'pending'
    AND (summary_next_attempt_at IS NULL OR summary_next_attempt_at <= now())
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSummaries(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPendingSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.SummaryShort,
			&i.SummaryLong,
			&i.SummaryStatus,
			&i.SummaryAttempts,
			&i.SummaryNextAttemptAt,
			&i.SummaryError,
			&i.SummaryLastErrorKind,
			&i.SummarizedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.source_id, p.title, p.url, p.author, p.summary_short, p.summary_long, p.summary_status, p.summary_attempts, p.summary_next_attempt_at, p.summary_error, p.summary_last_error_kind, p.summarized_at, p.tags, p.image_url, p.published_at, p.created_at, p.metadata, p.search_vector, s.name AS source_name, s.icon_url AS source_icon_url
FROM posts p
JOIN sources s ON p.source_id = s.id
WHERE
    ($3::uuid IS NULL OR p.source_id = $3) AND
    ($4::text IS NULL OR $4 = ANY(p.tags)) AND
    ($5::timestamptz IS NULL OR p.published_at < $5) AND
    ($6::timestamptz IS NULL OR p.published_at > $6)
ORDER BY p.published_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
	SourceID pgtype.UUID        `json:"source_id"`
	Tag      pgtype.Text        `json:"tag"`
	Before   pgtype.Timestamptz `json:"before"`
	After    pgtype.Timestamptz `json:"after"`
}

type ListPostsRow struct {
	ID                   uuid.UUID          `json:"id"`
	SourceID             uuid.UUID          `json:"source_id"`
	Title                string             `json:"title"`
	Url                  string             `json:"url"`
	Author               pgtype.Text        `json:"author"`
	SummaryShort         pgtype.Text        `json:"summary_short"`
	SummaryLong          pgtype.Text        `json:"summary_long"`
	SummaryStatus        string             `json:"summary_status"`
	SummaryAttempts      int32              `json:"summary_attempts"`
	SummaryNextAttemptAt pgtype.Timestamptz `json:"summary_next_attempt_at"`
	SummaryError         pgtype.Text        `json:"summary_error"`
	SummaryLastErrorKind pgtype.Text        `json:"summary_last_error_kind"`
	SummarizedAt         pgtype.Timestamptz `json:"summarized_at"`
	Tags                 []string           `json:"tags"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	PublishedAt          time.Time          `json:"published_at"`
	CreatedAt            time.Time          `json:"created_at"`
	Metadata             json.RawMessage    `json:"metadata"`
	SearchVector         interface{}        `json:"search_vector"`
	SourceName           string             `json:"source_name"`
	SourceIconUrl        pgtype.Text        `json:"source_icon_url"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Limit,
		arg.Offset,
		arg.SourceID,
		arg.Tag,
		arg.Before,
		arg.After,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.SummaryShort,
			&i.SummaryLong,
			&i.SummaryStatus,
			&i.SummaryAttempts,
			&i.SummaryNextAttemptAt,
			&i.SummaryError,
			&i.SummaryLastErrorKind,
			&i.SummarizedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.SearchVector,
			&i.SourceName,
			&i.SourceIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postExistsByURL = `-- name: PostExistsByURL :one
SELECT EXISTS(SELECT 1 FROM posts WHERE url = $1)
`

func (q *Queries) PostExistsByURL(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRow(ctx, postExistsByURL, url)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchPosts = `-- name: SearchPosts :many
SELECT p.id, p.source_id, p.title, p.url, p.author, p.summary_short, p.summary_long, p.summary_status, p.summary_attempts, p.summary_next_attempt_at, p.summary_error, p.summary_last_error_kind, p.summarized_at, p.tags, p.image_url, p.published_at, p.created_at, p.metadata, p.search_vector, s.name AS source_name, s.icon_url AS source_icon_url,
    ts_rank(p.search_vector, websearch_to_tsquery('english', $1)) AS rank
FROM posts p
JOIN sources s ON p.source_id = s.id
WHERE p.search_vector @@ websearch_to_tsquery('english', $1)
    AND ($4::uuid IS NULL OR p.source_id = $4)
    AND ($5::text IS NULL OR $5 = ANY(p.tags))
ORDER BY rank DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
	Limit              int32       `json:"limit"`
	Offset             int32       `json:"offset"`
	SourceID           pgtype.UUID `json:"source_id"`
	Tag                pgtype.Text `json:"tag"`
}

type SearchPostsRow struct {
	ID                   uuid.UUID          `json:"id"`
	SourceID             uuid.UUID          `json:"source_id"`
	Title                string             `json:"title"`
	Url                  string             `json:"url"`
	Author               pgtype.Text        `json:"author"`
	SummaryShort         pgtype.Text        `json:"summary_short"`
	SummaryLong          pgtype.Text        `json:"summary_long"`
	SummaryStatus        string             `json:"summary_status"`
	SummaryAttempts      int32              `json:"summary_attempts"`
	SummaryNextAttemptAt pgtype.Timestamptz `json:"summary_next_attempt_at"`
	SummaryError         pgtype.Text        `json:"summary_error"`
	SummaryLastErrorKind pgtype.Text        `json:"summary_last_error_kind"`
	SummarizedAt         pgtype.Timestamptz `json:"summarized_at"`
	Tags                 []string           `json:"tags"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	PublishedAt          time.Time          `json:"published_at"`
	CreatedAt            time.Time          `json:"created_at"`
	Metadata             json.RawMessage    `json:"metadata"`
	SearchVector         interface{}        `json:"search_vector"`
	SourceName           string             `json:"source_name"`
	SourceIconUrl        pgtype.Text        `json:"source_icon_url"`
	Rank                 float32            `json:"rank"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.WebsearchToTsquery,
		arg.Limit,
		arg.Offset,
		arg.SourceID,
		arg.Tag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.SummaryShort,
			&i.SummaryLong,
			&i.SummaryStatus,
			&i.SummaryAttempts,
			&i.SummaryNextAttemptAt,
			&i.SummaryError,
			&i.SummaryLastErrorKind,
			&i.SummarizedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.SearchVector,
			&i.SourceName,
			&i.SourceIconUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostSummary = `-- name: UpdatePostSummary :exec
UPDATE posts
SET summary_short = $2,
    summary_long = $3,
    tags = $4,
    summary_status = 'ready',
    summarized_at = now()
WHERE id = $1
`

type UpdatePostSummaryParams struct {
	ID           uuid.UUID   `json:"id"`
	SummaryShort pgtype.Text `json:"summary_short"`
	SummaryLong  pgtype.Text `json:"summary_long"`
	Tags         []string    `json:"tags"`
}

func (q *Queries) UpdatePostSummary(ctx context.Context, arg UpdatePostSummaryParams) error {
	_, err := q.db.Exec(ctx, updatePostSummary,
		arg.ID,
		arg.SummaryShort,
		arg.SummaryLong,
		arg.Tags,
	)
	return err
}

const updatePostSummaryFailed = `-- name: UpdatePostSummaryFailed :exec
UPDATE posts
SET summary_status = CASE WHEN $4::text = 'permanent' THEN 'failed' ELSE 'pending' END,
    summary_attempts = summary_attempts + 1,
    summary_error = $2,
    summary_last_error_kind = $4,
    summary_next_attempt_at = $3
WHERE id = $1
`

type UpdatePostSummaryFailedParams struct {
	ID                   uuid.UUID          `json:"id"`
	SummaryError         pgtype.Text        `json:"summary_error"`
	SummaryNextAttemptAt pgtype.Timestamptz `json:"summary_next_attempt_at"`
	SummaryLastErrorKind pgtype.Text        `json:"summary_last_error_kind"`
}

func (q *Queries) UpdatePostSummaryFailed(ctx context.Context, arg UpdatePostSummaryFailedParams) error {
	_, err := q.db.Exec(ctx, updatePostSummaryFailed,
		arg.ID,
		arg.SummaryError,
		arg.SummaryNextAttemptAt,
		arg.SummaryLastErrorKind,
	)
	return err
}
