// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (kind, name, site_url, feed_url, icon_url, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, name, site_url, feed_url, icon_url, is_active, created_at, last_polled, metadata
`

type CreateSourceParams struct {
	Kind     string          `json:"kind"`
	Name     string          `json:"name"`
	SiteUrl  pgtype.Text     `json:"site_url"`
	FeedUrl  pgtype.Text     `json:"feed_url"`
	IconUrl  pgtype.Text     `json:"icon_url"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Kind,
		arg.Name,
		arg.SiteUrl,
		arg.FeedUrl,
		arg.IconUrl,
		arg.Metadata,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.SiteUrl,
		&i.FeedUrl,
		&i.IconUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastPolled,
		&i.Metadata,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, name, site_url, feed_url, icon_url, is_active, created_at, last_polled, metadata FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.SiteUrl,
		&i.FeedUrl,
		&i.IconUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastPolled,
		&i.Metadata,
	)
	return i, err
}

const listActiveRSSSources = `-- name: ListActiveRSSSources :many
SELECT id, kind, name, site_url, feed_url, icon_url, is_active, created_at, last_polled, metadata FROM sources WHERE kind = 'rss' AND is_active = true
`

func (q *Queries) ListActiveRSSSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listActiveRSSSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.SiteUrl,
			&i.FeedUrl,
			&i.IconUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastPolled,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, kind, name, site_url, feed_url, icon_url, is_active, created_at, last_polled, metadata FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.SiteUrl,
			&i.FeedUrl,
			&i.IconUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastPolled,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceFeedURL = `-- name: UpdateSourceFeedURL :exec
UPDATE sources SET feed_url = $1 WHERE id = $2
`

type UpdateSourceFeedURLParams struct {
	FeedUrl pgtype.Text `json:"feed_url"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSourceFeedURL(ctx context.Context, arg UpdateSourceFeedURLParams) error {
	_, err := q.db.Exec(ctx, updateSourceFeedURL, arg.FeedUrl, arg.ID)
	return err
}

const updateSourceLastPolled = `-- name: UpdateSourceLastPolled :exec
UPDATE sources SET last_polled = now() WHERE id = $1
`

func (q *Queries) UpdateSourceLastPolled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSourceLastPolled, id)
	return err
}
